server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: auth-signin
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/sign-in
        - id: auth-signup
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/sign-up
        - id: auth-forgot-password
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/forgot-password
        - id: auth-reset-password
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/reset-password
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/carts/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/categories/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG